### ISSUE TITLE
update notice everytime

### ISSUE THREAD

**Issue by Da1ong** [TheCheatsrichter/Gw2_Launchbuddy#30]
Every time when I start the Launchbuddy, it always tells me to update the game client which is up to date actually. Do you have any idea about that?
![111](https://cloud.githubusercontent.com/assets/25359938/22320246/7f53273c-e358-11e6-8604-3d4c38d6def8.jpg)

**Comment by TheCheatsrichter** [comment]
Launchbuddy actually compares the client version written in the xml file at %appdata%\Guild Wars 2 with the clientversion provided by the API. So either one of the three things can cause this error:

1. Your gw2 client somehow does not write to the xml file.
2. The API wasn't updated correctly by arenanet.
3. You are using the chinese client which version might not be equal to the versionnumber provided by the api.

**Comment by KairuByte** [comment]
I also don't see a way to properly determine which client type this is, unless there is a property set in the chinese client's xml that is not set in the normal one?

**Comment by Da1ong** [comment]
it got fixed when I changed my system language to English. Thanks for ur help.

**Comment by KairuByte** [comment]
That is actually somewhat concerning as it means we cant properly check on non english pc's.

**Comment by TheCheatsrichter** [comment]
My mother language is german so it might has something to do with the special charset of some languages.

**Comment by TheCheatsrichter** [comment]
`MessageBoxResult win = MessageBox.Show("A new Build of Gw2 is available! Not updating can cause Gw2 Launchbuddy to not work! Update now?", "Client Build Info", MessageBoxButton.YesNo, MessageBoxImage.Question);
                        if (win.ToString() == "Yes")
                        {
                            updateclient();
                            loadconfig();
                            checkversion();
                        }`

I might wanna check if this lines of code actually work on different charactersets.

**Comment by Da1ong** [comment]
It was solved when I changed my pc language to English.

**Comment by TheCheatsrichter** [comment]
I know, but the error still is in the code and therefore isn't solved. The language shouldnt determine if the update function works or not.

**Comment by Da1ong** [comment]
btw, I cannot login with selecting authentication server today. Do you know why?

**Comment by TheCheatsrichter** [comment]
The login servers aren't in the best condition at the moment. Yesterday multiple people reported login issues with them. Try to choose another.
