### ISSUE TITLE
V3.2.2 LB fails to press Login button 

### ISSUE THREAD

**Issue by morpheus305** [TheCheatsrichter/Gw2_Launchbuddy#405]
**Describe the bug**
V3.1 I started having the 80 percent issue but the accounts would login in just fine. On Nov 29 when Anet released the new gw2 patch I started having a problem where the clients would open but LB failed to login them in so you would have to manually click the login button. Then with V3.2.2 it opens the client and does something weird and I suspect cause it's missing the step of hitting the login button. Instead after about 10 seconds after the client it opens it insteads just changes the login information in the gw2 client which causes the client to fail. Here is a screenshot of it https://gyazo.com/6321545d275154be35981a54d3d873f9 When this happens you can't even manually click the login button. The only I have found around is it clicking the login button manually as soon as the gw2 client opens. This has really broke LB for me as it makes a real pain to login all my clients every day.

**To Reproduce**
1: Open LB
2: Launch an account
3: It will open the gw2 client, it will not click the login button on the gw2 client and instead after 10 seconds will fill in 2 characters into the password box of the gw2 client.

**Expected behavior**
I expect LB to open the gw2 client and login the client successfully like it's always been able to do.

**First happend in LB Version**
Part of the problem started in V3.1.0 after Nov29th gw2 patch and got worse after V.3.2.2

**Screenshots**
Here is another link of the screenshot https://gyazo.com/6321545d275154be35981a54d3d873f9

**Comment by TheCheatsrichter** [comment]
Did you change any third party software like arcdps, blishhud etc? I am currently working on supporting these, as these seem to modifiy the order in which libraries are loaded into the game client. (this is what LB uses to determine the state of the game client)

**Comment by TheCheatsrichter** [comment]
Just tested a few possible workflows. Only time I was able to reproduce an issue which closely resembles oyur description when the known issue https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/383 kicked in. Do you by any chance use a DPI scaling on windows?

**Comment by Tristan-Louvre** [comment]
Firstly, I just want to say thank you and that I am very grateful for the tool that you have developed. I have the same issue as @morpheus305. I am running Windows 10 Pro 22H2. I recently jumped from 3.0.6 and found that the issue cropped up on 3.1.0, so I reverted.

I am now committed to your new version (as I really want those DAT file / Update improvements) but have been finding this particular issue to be quite the nuisance.

I am pretty sure I don't have DPI scaling turned on in any way but I will say based off of your comment above the issue could lie with the additional software I have running (arcdps, blishhud, arcdps uploader and arcdps boon table). In 3.0.6 this never prevented logins though, so this has to be a change in interaction that was introduced with the new versions. 

If this is true and we diagnose it I suggest adding it to the README.md as it could be a stumbling block for a number of updating users.

Lastly, I will say that my Gamewindow settings also don't always correctly set themselves up on most executions (at least 1 of my 13 accounts gets stretched or misplaced). Could this be linked to the same problem?

I will test your suggested fix and revert back.

Thank you!

**Comment by TheCheatsrichter** [comment]
Heyo thanks for the kind words and the report!
I am currently still searching for a workflow that also causes the same issue without dpi scaling. As long as I don't know what causes this issue under the hood of the gw2 gameclient or launchbuddy bug fixes will be quite hard...
So I will keep you updated on my newest findings. Main problem atm is time as I am bussy keeping my private life together.

The gamewindowsetting is also dependend on the same code as the loginfile creation. If LB reads the state of the gameclient wrong these features will be applied to early and will get discarded because the gamewindow itself sets its size once the char selection screen is reached.

Any additional info is appreciated.

**Comment by Tristan-Louvre** [comment]
So I just followed your suggested solution with separating out the .dll's into their own folder and applying them to the intended accounts and it solved the login problem for me. I will keep an eye on my account logins this week and provide further feedback if anything acts weird. For the gamewindowsetting issue I used to have the dpiScaling setting for accounts set to true. I am going to try setting that to false and seeing if that potentially also has an impact on the screen sizing state.

**Comment by morpheus305** [comment]
Don't have dpiScaling turned on in Windows but I do in gw2. I turned it off just to see if that would fix it but it didn't help. What did help was removing arcdps and boontable. It started working fine so I tried adding them back in through the tutorial like you suggested but went back to having the same problems. Though I am not sure I did it correctly. Can you remove the .dll's and then add them back in all while LB is open cause that's what I did.

**Comment by Tristan-Louvre** [comment]
@morpheus305 are you keeping the .dll's in a different folder completely? I am now keeping them separate from my guild wars 2 folder and adding it in with the injected software segment on LB.

**Comment by tazer1** [comment]
Hello, so I am having exactly thw same problem as OP - initually login screen looks fine, but after ~10 sec it changes to blank username and 2 characters entered as password. If I manually press Login and Play during theses 10 sec everything works fine, otherwise it fails to launch the game. I use BlishHUD, arcdps and recently kp.me module too, but even when I deleted all of their .dll from main Guild Wars 2 folder, or set them up in a completely different folder and pointed towards it in account settings injected software section as suggested I am still getting the same behavior. I really tried to keep it as clear as possible, so at one point there was also addons with their .dlls at all and no BlishHUD path in launchbuddy and ticked it off in TacO+Blish section and still no luck. Problems with having to manually pressing Login+Play started with,3.1.0, but initially it would just not progress, now it "progresses" to this blank longin + 2 characters screen as in attached screenshot in OP's post. And finally I tested DPI scaling as I had it in Windows set to 125% so set it to 100% and still the same (but it was always at 125% and I never had an issue with GW2 to be honest)
The way I see the possible fix for this - as soon as launchbuddy "presses" login+play fast enough (faster than 10 sec and ideally with no delay?) it should work fine, because this delay is what seems to be a problem for me. Hope this info helps :)

**Comment by morpheus305** [comment]
UPDATE: Injecting the .dll's from outside of the gw2 folder fixed the problem. I only tried it one time so will see how it goes. I have one more question if you don't mind. Cheat is LB now always going to to do full check on every login file when you open up LB everytime? It used to only do that when gw2 got a patch which made sense. For people with a lot of accounts it can take a while.

**Comment by TheCheatsrichter** [comment]
Editing Title because I found the cause of the issue of the first post.

I want to make sure that everybody understands that we have a mixed bag of issues here:

1) Gameclient launches with filled out Email and Password, the login does however not automatically happen. After some time the email and password field get deleted and two dots are entered. This is a timing issue which only presses the login button once. LBs config currently was to fast for slower machines and sometimes did miss it --> New version will introduce a automated retry (up to 5 times) before proceeding with filling out the game client form.

2) The gameclient launches with a blank email/ password field. This is not an Launchbuddy issue. The issue is in the gameclient itself and somehow is linked to the DPI setting: https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/383. If you want this fixed please create a bug report in the gw2 gameclient to create some pressure.

3) The progress of the gameclient gets stuck at some percentage. Likely caused by third party .dlls which mess up LBs gameclient tracker. Without the gameclienttracke LB doesnt know when to press which buttons.

@morpheus305 : https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/392

**Comment by TheCheatsrichter** [comment]
Pushed 3.2.4 with a fix for error nr 1

**Comment by tazer1** [comment]
> Pushed 3.2.4 with a fix for error nr 1

Unfortunately with 3.2.4 it still behaves the same way for me :/ Login info entered correctly, 10 sec of waiting, blank username and 2 characters as password that does nothing. Tried with both automatically updated version and downloaded new .exe and run manually.

**Comment by Tristan-Louvre** [comment]
Just a reminder, my problem was number 1 and 3. This was solved with fixing the .dll's. So there might be some interplay between the issues. I suggest users to begin with the DPI debug and then do the .dll debug.

**Comment by tazer1** [comment]
I just tried again with no .dlls with main folder, no BlushHUD marked for launch in Launchbuddy and closed in taskbar, no .dlls injected from external folder where now they reside and no change in behavior, still getting Issue #1, Launchbuddy is still not logging in and pressing play button on its own. So I don't know why at some point it decides to wipe correctly placed e-mail and password (so no issue with DPI that I also tested earlier). From my perspective it really just needs to push these buttons after a second or two, everything else works fine, including external .dlls

**Comment by morpheus305** [comment]
Sorry bot but this is still an issue. Hopefully it will get addressed soon.
