### ISSUE TITLE
"Unable to check for Launchbuddy Updates"

### ISSUE THREAD

**Issue by wohali** [TheCheatsrichter/Gw2_Launchbuddy#61]
This error started today on launch:

```
"Unable to check for Launchbuddy Updates. Please check your internet connection"
```

I'm not sure what changed; I'm still able to access the [releases URL](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases) on the same machine through a browser, as defined [here](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/master/Gw2%20Launchbuddy/Versionswitcher.cs#L16).

**Comment by Invisi** [comment]
It seems like WebClient's default behavious is using TLSv1 and GitHub [just recently removed support for TLSv1 and TLSv1.1](https://github.com/blog/2507-weak-cryptographic-standards-removed).
Adding `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;` resolves that in my local build.

**Comment by SaiyanOfDarkness** [comment]
I'm just gonna take a wild guess, that it'll be addressed in next release, as it isn't really that big of a deal if you just keep LB running in the background.

**Comment by TheCheatsrichter** [comment]
Fixed in 924c90947a4abe4a9b166f1b3828f28858891630
Thanks for the Report.

**Comment by kazerniel** [comment]
This error message still appears for me in v1.5.3. (Btw I'm on Win7 x64.)
